#!/usr/bin/python3 -u

# @file pair_tool
# @author Spartan State Security Team
# @brief host tool for pairing a new key fob
# @date 2023
#
#  This source file is part of our designed system
#  for MITRE's 2023 Embedded System CTF (eCTF).

import socket
import struct
import argparse
import sys
import time


# @brief Function to send commands to pair
# a new fob.
# @param unpairmed_fob_bridge, bridged serial connection to unpairmed fob
# @param pairmed_fob_bridge, bridged serial connection to pairmed fob
# @param pair_pin, pin used to pair a new fob
def pair(unpaired_fob_bridge, paired_fob_bridge, pair_pin):

    # Connect to both sockets for serial
    unpaired_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    unpaired_sock.connect(("ectf-net", int(unpaired_fob_bridge)))
    unpaired_sock.settimeout(2)

    paired_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    paired_sock.connect(("ectf-net", int(paired_fob_bridge)))
    paired_sock.settimeout(2)

    # Send pair commands to both fobs
    unpaired_sock.send(b"\x30")
    paired_sock.send(b"\x20")

    # Send pin to the paired fob
    time.sleep(0.2)
    pair_pin_bytes = struct.pack('<I',int(pair_pin,16))
    paired_sock.send(pair_pin_bytes)
    time.sleep(0.2)

    return 0


# @brief Main function
#
# Main function handles parsing arguments and passing them to pair
# function.
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--unpaired-fob-bridge",
        help="Bridge for the unpaired fob",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--paired-fob-bridge",
        help="Bridge for the paired fob",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--pair-pin", help="Program PIN", type=str, required=True,
    )

    args = parser.parse_args()

    pair(args.unpaired_fob_bridge, args.paired_fob_bridge, args.pair_pin)


if __name__ == "__main__":
    main()
